### ISSUE TITLE
Bound must be positive

### ISSUE THREAD

**Issue by Sunconure11** [LlamaramaTeam/Llamarama#32]
https://bytebin.lucko.me/ao3COGCCRM

**Comment by 0xJoeMama** [comment]
Thank you for your report. I would like it if you could provide the same crash report once again since I wish to take a look at the issue again to make sure I have implemented a valid fix.

**Comment by 0xJoeMama** [comment]
#35 Resolves this however I'd still like to see the crash report again before I merge.

**Comment by Sunconure11** [comment]
Currently dealing with an issue in another mod, so I might not be able to recreate it for a few days. Plus it basically happened out of the blue. I don't know how easily it can be replicated.

**Comment by 0xJoeMama** [comment]
Do you not have the old log file?

**Comment by 0xJoeMama** [comment]
Or can you not find it?
If you can't find it, it's okay I am just being paranoid before I commit to a release and state the issue is fixed.

**Comment by Sunconure11** [comment]
I have so many logs that I'm not sure which one it would be.

**Comment by 0xJoeMama** [comment]
Yeah I figured that would be the issue. Don't worry, I think the issue is fixed. However just so you know, not just for this repo but for others as well, until your issue is closed, do NOT delete/remove any pertinent information.

**Comment by 0xJoeMama** [comment]
This time the auto-delete got you.
